### PR TITLE
Poke appveyor

### LINKED ISSUE #569: Build checks split for appveyor
Note how the AppVeyer CI builds are split in two. Looking at the screenshot below, the first row has the "Required" tag but not "Details". This is reversed for the second row. The Travis build seems to be working correctly.

screen shot 2015-11-09 at 11 01 42 pm

### PR DESCRIPTION
**Pull request by advayDev1**
Should fix #569

### CODE REVIEW

**Comment by advayDev1** [comment]
Just needed to update our branch protection config, and then poke Appveyor

**Comment by brunobowden** [comment]
Looks like it's working but will confirm when the CI is complete.

screen shot 2016-01-08 at 8 22 33 pm

**Comment by advayDev1** [comment]
Travis is failing to talk to plugins.gradle.org again, but Appveyor seems fine.

**Comment by brunobowden** [comment]
LGTM

**Pull request merged**
