### PR TITLE
Public modifiers, parentheses and IllegalArgumentException

### PR DESCRIPTION
**Pull request by brunobowden**
Several basic style fixes:

- Remove ‘public’ modifiers:
http://www.groovy-lang.org/style-guide.html#_public_by_default

- Parentheses for function calls:
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/CONTRIBUTING.md#style-guidelines

- IllegalArgumentException => InvalidUserDataException

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - for your pleasure, basic style changes, mostly as directed by our style guidelines

**Comment by advayDev1** [comment]
LGTM

**Comment by advayDev1** [comment]
I know this is the style we agreed to, but i can't help but feel logger.debug(...) is less readable than logger.debug ...

**Comment by brunobowden** [comment]
@advayDev1 - the world has managed to log with parentheses for a long time now, I still it'll survive a little longer with some more ;-)

**Pull request merged**
