### PR TITLE
Simplify README + other docs improvements

### PR DESCRIPTION
**Pull request by brunobowden**
README:
- Hard code the version number in README
- Fix J2objcConfig.groovy reference
- Move task disable and Basic Cycle Finder from README to FAQ

Other:
- J2objcConfig class documentation
- Improved translateArgs examples
- Style consistencies in FAQ

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - simplify the README to focus on the most important information.

**Comment by confile** [comment]
@brunobowden LGTM beside the following question would be interesting in Readme: "How do I configure proguard?" This is still a question I am not sure about.

**Comment by brunobowden** [comment]
This is something that should go in the FAQ. I'd welcome that from you or
Advay.

**Comment by advayDev1** [comment]
proguard is a distant priority for most people.  let's tackle the more important stuff right now.

LGTM

**Pull request merged**
