### PR TITLE
Guava 19.0

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by brunobowden** [comment]
This is showing a merge conflict - can you rebase it?

**Comment by advayDev1** [comment]
Don't review this yet @brunobowden  - this is just a demo for the j2objc folks of the build break on 19.0rc1

**Comment by brunobowden** [comment]
I'm just excited to see the progress ;-)

**Comment by brunobowden** [comment]
cc @tomball, @kstanger

**Comment by brunobowden** [comment]
Version "19.0-rc2" was published the end of September.

@advayDev1 - can you please confirm whether this issue still exists. If so, then we should coordinate with @tomball and @kstanger to see about getting this resolved.

**Comment by advayDev1** [comment]
My own tests showed things are fine.  I still don't think we should submit anything until Guava is released.

**Comment by brunobowden** [comment]
@advayDev1 - Aug 28th comment, you mentioned a build break. Is that now fixed? Is it possible to get a clean build in this PR? It would be nice to confirm that before 19.0 is released.

**Comment by advayDev1** [comment]
That build break was fixed by @kstanger in https://github.com/google/j2objc/commit/0c2c7b16afde033caf6a6c78a13644c47607a85d

**Comment by brunobowden** [comment]
From that PR, it looks as though this was included within 0.9.8.2.1? If you update this PR with that change, will it now work? I understand about delaying merge until the official 19.0 release.

**Comment by brunobowden** [comment]
@advayDev1 - do you want to keep this open or close this?

**Comment by advayDev1** [comment]
Since they released full 19.0, I updated the config.
If it works, let's merge, if not, I won't have time to debug right now.

**Comment by brunobowden** [comment]
LGTM assuming that the build works

**Comment by brunobowden** [comment]
CI passed. Good news. Please merge at your leisure.

**Comment by advayDev1** [comment]
heh, pleasantly surprised.

**Pull request merged**
