### PR TITLE
Fix TestTask for zero tests + Regex Refactor

### PR DESCRIPTION
**Pull request by brunobowden**
- Standardize on slashyString for regex
- Utils.escapeSlashyString(…)
- Improve regex fail messages
- Regex capturing group comments

Introduce @Rule for exception handling:

@Rule
public ExpectedException expectedException = ExpectedException.none();

TESTED=added a few tests:
- testTaskAction_ZeroTestExpected
- testTaskAction_ZeroTestUnexpected

### CODE REVIEW

**Comment by brunobowden** [comment]
@confile, @advayDev1 - PTAL

**Comment by brunobowden** [comment]
Fixes #261

**Comment by confile** [comment]
LGTM

**Comment by confile** [comment]
@advayDev1 what do you think?

**Comment by advayDev1** [comment]
lgtm

**Pull request merged**
