### PR TITLE
testVerifyXcodeArgs

### PR DESCRIPTION
**Pull request by brunobowden**
- Checks that helpful exception is given if j2objcConfig not configured for Xcode

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - this is an easy PR

**Comment by confile** [comment]
LGTM

**Comment by brunobowden** [comment]
@advayDev1 - PTAL

**Comment by advayDev1** [comment]
lgtm

**Comment by brunobowden** [comment]
Error message changed from 'TARGET-NAME' to 'IOS-APP-TARGET' so that it's more clear. Now merged.

**Comment by brunobowden** [comment]
Left behind some commits that I meant to FIXUP. Ugly but probably best to leave them as I prefer not to much with the history.

**Pull request merged**
