### PR TITLE
version = '0.4.4-alpha-SNAPSHOT'

### PR DESCRIPTION
**Pull request by brunobowden**
I know we'll next go to v0.5.0 but leaving it as the old version until we make that leap.

### CODE REVIEW

**Comment by advayDev1** [comment]
no the correct thing would be to label it `0.4.4-alpha-SNAPSHOT` then.  you have to monotonically increase- and X-SNAPSHOT is always below X.

**Comment by brunobowden** [comment]
version => 0.4.4-alpha-SNAPSHOT

**Comment by brunobowden** [comment]
Can I get an LGTM for this?

**Comment by advayDev1** [comment]
lgtm

**Comment by advayDev1** [comment]
we screwed this up a bit.  the 'bump to snapshot' cl always has to be submitted immediately after the 'bump to released version' cl.  when there are commits in between, namely: 
https://github.com/j2objc-contrib/j2objc-gradle/compare/34e792c40d6c24b904cbc0c877423b1686831429...d9c4bfe50e6fbb3edf67f0934b785e3bf74e4c8f
builds at those commits are falsely attributed to the previous released version (a problem when we debug other users' logs)

**Pull request merged**
