### PR TITLE
simple1 Xcode build

### PR DESCRIPTION
**Pull request by brunobowden**
- simple1 Xcode project, iOS App and iOS App Tests
- simple1 build modified to update Xcode project

Partial fix for #507 - automatic Xcode app and test build

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - please setup the mixc build of the Xcode project. For bonus points, it would also be great to run the tests also. Finally, please look at how this should integrate with the `run-test.sh` script.

**Comment by advayDev1** [comment]
mixc-build will indeed build and run the OSX Xcode unit tests.  It won't (can't) do anything with iOS, since that requires a simulator.

also, it will be interesting getting the build working on Travis, considering we'll have to finagle with the Developer Identity (signing).

LGTM.

**Comment by advayDev1** [comment]
btw i'm not actually reviewing all the Xcode spew.

**Comment by advayDev1** [comment]
Issue #507

**Pull request merged**
