### PR TITLE
README nits

### PR DESCRIPTION
**Pull request by brunobowden**

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - simple change

**Comment by advayDev1** [comment]
ah ... sorry, I meant LGTM

**Comment by brunobowden** [comment]
That'll even out our mistake count ;-)

**Comment by advayDev1** [comment]
i think i still get one delete-the-repo mistake =P

**Comment by brunobowden** [comment]
Oh boy... glad I did that one when not too many people were looking.

**Pull request merged**
