### PR TITLE
Fix local development instructions

### PR DESCRIPTION
**Pull request by brunobowden**

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - this a simple change to fix the local development instructions

**Comment by confile** [comment]
LGTM

**Comment by advayDev1** [comment]
Interesting, i just use the classpath setting and never the plugins { ... } syntax and it works fine for me.
Either way, if this is working for you - LGTM.

**Comment by brunobowden** [comment]
The plugins syntax makes for very concise instructions for the plugin
users. Merging now.

**Comment by advayDev1** [comment]
Oh then this is me misreading your instructions:
```
    // Comment out for local development
    //plugins {
    //    id 'java'
    //    id 'com.github.j2objccontrib.j2objcgradle' version 'X.Y.Z-alpha'
    //}
```
I interpreted that for some reason as to uncomment the comments, not as in instruction to comment this (usually uncommented) section.  SG!

**Pull request merged**
