### PR TITLE
Changelog for new features

### PR DESCRIPTION
**Pull request by advayDev1**
Forward-looking ;)

### CODE REVIEW

**Comment by advayDev1** [comment]
lol shouldn't we hold off merging until the PRs are in?

**Comment by brunobowden** [comment]
Oh shoot, my mistake. I wish that was a GitHub setting.

**Comment by advayDev1** [comment]
well know you've got to get #512 in :)

**Comment by brunobowden** [comment]
Main blocker for that is to get it tested. There's some setup with that.

**Pull request merged**
