### PR TITLE
Url

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by brunobowden** [comment]
Why do we need to bring j2objccontrib.org in to it at all? Given that we're already so tightly integrated with GitHub, I don't see that changing... so I'm not sure what value this adds?

**Comment by advayDev1** [comment]
Just easier to remember urls really

**Comment by brunobowden** [comment]
I still think we're better off with the GitHub urls and people are more likely to be comfortable clicking on that. Unless we're building out the website, I don't think it has much value to add in another url.

**Comment by advayDev1** [comment]
fair enough

**Pull request closed without merging**
