### PR TITLE
added flag to skip tests

### PR DESCRIPTION
**Pull request by confile**

### CODE REVIEW

**Comment by advayDev1** [comment]
the correct way to do this is now to just run `j2objcAssemble` (which does not run the test).  if you run `build` tests are supposed to be run.  you can skip them by doing ex: `./gradlew build -x j2objcText`

**Comment by brunobowden** [comment]
Is there a way of having cycleFinder default disabled and then enabled by
config if needed? Or do we need to keep that flag?

**Comment by advayDev1** [comment]
when creating the task in the plugin you could do `enabled = false`, but...

i'd argue the right thing to do is leave the cycleFinder out of the dependency of the translation step by default.  similar to how we removed tests from translation.

**Comment by advayDev1** [comment]
@confile, Also if you want to permanently skip j2objc tests for a particular build.gradle, put this:
```
j2objcTest {
    enabled false
}
```

You can do this with any named task (i.e. you can configure it after plugin application in your own build file).

Since this is already supported the standard gradle way, closing.  Please reopen as needed.

**Comment by confile** [comment]
@advayDev1 Why did you close this pull request? We should be consistent for cycle finder we have a skip flag as well.

**Comment by advayDev1** [comment]
CycleFinder's skip flag is going away too, about to file the PR.

The right way to do this is as above, and I'm adding the functionality to do that.

**Comment by advayDev1** [comment]
See #145

**Comment by confile** [comment]
ok

**Comment by confile** [comment]
@advayDev1 You should add: 
```
j2objcTest {
    enabled false
}
```
to the docs.

**Comment by advayDev1** [comment]
Can you make the PR?

**Comment by confile** [comment]
@advayDev1 yes. Since you are an expert with git. I made a fork of the master. How can I update my master fork that it contains the latest commits?

**Comment by brunobowden** [comment]
You should do all the development on a branch and not use master. That's
both safer and easier for you.

Then follow the instructions in CONTRIBUTING.md to rebase your master and
branches on the upstream changes.

**Comment by advayDev1** [comment]
First
git fetch upstream/master
Then
git checkout master
git merge upstream/master

Note that you really should create a new branch for every PR, otherwise the
instructions in contributing.MD will not work.

**Comment by confile** [comment]
@advayDev1 Thanks!

**Comment by confile** [comment]
@brunobowden I create a branch for each pull request, but I forked your master first and created branches from this fork.

**Pull request closed without merging**
