### PR TITLE
mixc build for simple1 -DO NOT MERGE

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by advayDev1** [comment]
@brunobowden - this is currently failing due to a number of missing pods files.  You should be able to checkout this branch locally and then get the pods side of the build working, check that part in, and then I can merge this on top.

Here are the errors re: pods I see:
```
Failed to run xcodebuild:
Build settings from command line:
    SDKROOT = iphoneos9.0

=== BUILD TARGET IOS-SIMPLE1 OF PROJECT IOS-SIMPLE1 WITH CONFIGURATION Debug ===

Check dependencies
The file “Pods-IOS-SIMPLE1.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/Pods/Target Support Files/Pods-IOS-SIMPLE1/Pods-IOS-SIMPLE1.debug.xcconfig)

Write auxiliary files
/bin/mkdir -p /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Objects-normal/armv7
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Objects-normal/armv7/IOS-SIMPLE1-OutputFileMap.json
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1-all-target-headers.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-FF813721D4FD069F235419B3.sh
chmod 0755 /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-FF813721D4FD069F235419B3.sh
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/swift-overrides.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Objects-normal/armv7/IOS-SIMPLE1.LinkFileList
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1-project-headers.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1-generated-files.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1-own-target-headers.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1-all-non-framework-target-headers.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/IOS-SIMPLE1.hmap
write-file /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-7519B8B16C423C3E1A2EDB6A.sh
chmod 0755 /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-7519B8B16C423C3E1A2EDB6A.sh

Create product structure
/bin/mkdir -p /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/Debug-iphoneos/IOS-SIMPLE1.app

PhaseScriptExecution Check\ Pods\ Manifest.lock build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-FF813721D4FD069F235419B3.sh
    cd /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1
    /bin/sh -c /Users/USERNAME/gitHubPublicRepos/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphoneos/IOS-SIMPLE1.build/Script-FF813721D4FD069F235419B3.sh
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

** BUILD FAILED **

```

**Comment by brunobowden** [comment]
I'll take a look later this weekend.

How about renaming the 'app' directory to 'ios-build', since the former name suggests that it might do the Android build also?

**Comment by brunobowden** [comment]
I've seen this cause multiple build failures:

```
* What went wrong:
Error resolving plugin [id: 'com.gradle.plugin-publish', version: '0.9.0']
> Could not GET 'https://plugins.gradle.org/api/gradle/2.4/plugin/use/com.gradle.plugin-publish/0.9.0'.
   > The target server failed to respond
```

**Comment by advayDev1** [comment]
Absolutely; it is not a travis issue though.  When it occurs, my local machine also cannot access plugins.gradle.org.  I'm guessing their servers aren't handling the load.

**Comment by brunobowden** [comment]
@advayDev1 - please try this again. I might work now that the build will generate the podspec files and also Cocoapods is installed. The PR also needs rebasing as well. Just ping the conversation when you see any error and I'll look in to it.

**Comment by brunobowden** [comment]
I found the build in Travis and restarted it. We'll see what it does.

**Comment by brunobowden** [comment]
The newly kicked off doesn't have my recent changes. You'll need to rebase the branch on upstream/master to get that.

**Comment by brunobowden** [comment]
I think the `build.gradle` should be in the `ios` directory instead of `app`. I think the `app` directory should only be for Android while all the iOS related code and build should be in its' own directory.

**Comment by brunobowden** [comment]
Last build error:

_Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) were found._

The Travis common build errors lists a solution:

http://docs.travis-ci.com/user/common-build-problems/#Mac%3A-Code-Signing-Errors

**Comment by brunobowden** [comment]
@advayDev1 - I know you want to focus on other stuff... but it would be great to get this in. This is the last major piece that we need for testing coverage. I think it's a small change to get it work. Once it's in place, then I'll replicate it for the allPlatforms test. Having this merged in will the last thing we need for major test coverage in my opinion.

**Comment by advayDev1** [comment]
@brunobowden - I don't intend on putting any of my keys on Travis as instructed here: https://www.objc.io/issues/6-build-tools/travis-ci/ .  However, I will try the iphonesimulator-only build.  IIRC mixc supports that.

**Comment by advayDev1** [comment]
One of my key problems on this is that now that the system tests use cocoapods I can't run any of them locally.  So it is a long cycle to push to Travis for each attempt.

**Comment by advayDev1** [comment]
@brunobowden - I think you need to take over this PR.  Now that we're past the signing issue, I'm getting a pods-related error that I cannot debug locally:

```
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.0.sdk -L/Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/Debug-iphonesimulator -L/Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/localJ2objcDist/j2objc-0.9.8.2.1/lib -F/Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/Debug-iphonesimulator -filelist /Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphonesimulator/IOS-SIMPLE1.build/Objects-normal/x86_64/IOS-SIMPLE1.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -lObjC -lguava -licucore -ljavax_inject -ljre_emul -ljsr305 -lz -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphonesimulator/IOS-SIMPLE1.build/Objects-normal/x86_64/IOS_SIMPLE1.swiftmodule -lPods-IOS-SIMPLE1 -Xlinker -dependency_info -Xlinker /Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/IOS-SIMPLE1.build/Debug-iphonesimulator/IOS-SIMPLE1.build/Objects-normal/x86_64/IOS-SIMPLE1_dependency_info.dat -o /Users/travis/build/j2objc-contrib/j2objc-gradle/systemTests/simple1/ios/IOS-SIMPLE1/build/Debug-iphonesimulator/IOS-SIMPLE1.app/IOS-SIMPLE1
ld: library not found for -lPods-IOS-SIMPLE1
```

**Comment by advayDev1** [comment]
Looks like a few things will need to be resolved:
- Appropriate 'schemes' for the workspace need to be saved in 'shared' mode so they get checked in.  Not sure if you expect the user to create these or to configure Xcode to create them, or the Xcode tasks are supposed to take care of that.
- There are two workspaces in the simple1 directory: https://github.com/j2objc-contrib/j2objc-gradle/tree/master/systemTests/simple1/ios/SIMPLE1.xcworkspace and https://github.com/j2objc-contrib/j2objc-gradle/tree/master/systemTests/simple1/ios/IOS-SIMPLE1/IOS-SIMPLE1.xcworkspace - which is the right one?
- mixc needs to have a workspace argument added to it.

**Comment by brunobowden** [comment]
@advayDev1 - I'm holding off on this for now but will get back to it later

**Comment by brunobowden** [comment]
@advayDev1 - do you want to keep this open or close this?

**Comment by advayDev1** [comment]
The code's always there, but I don't think either of us have time to do finish this.  Closed.

**Pull request closed without merging**
