### PR TITLE
Merge current v0.3.0-alpha branch into master

### PR DESCRIPTION
**Pull request by advayDev1**
There have been major changes to the release branch, merging early/often will make sure our work on master doesn't get disrupted.

### CODE REVIEW

**Comment by advayDev1** [comment]
Note I'm not deleting the release branch after this - just keeping master up to date with the fixes

**Comment by brunobowden** [comment]
I checked the PR numbers and not the contents and this looks correct. It's more complicated as we have merges going in both directions. In future, I don't think we should branch until we believe we're absolutely done.

**Comment by brunobowden** [comment]
LGTM

**Comment by advayDev1** [comment]
Yes, you're right about branching late.
We do need to think about what to do with features we don't want in the release though...

**Pull request merged**
