### PR TITLE
v0.6.0-alpha version increment and changelog

### PR DESCRIPTION
**Pull request by brunobowden**
@advayDev1 - please sign off on this

@himamis - your fix will be public in v0.5.1

### CODE REVIEW

**Comment by advayDev1** [comment]
lgtm, but i'm not sure if you were respinning or not

**Comment by brunobowden** [comment]
I will respin but I wanted to get #565 merged in first

**Comment by brunobowden** [comment]
I've amended the version number to 0.6.0 as this is adding functionality. According to semver.org, this merits an increment a MINOR increment.

I will submit this and respin once all the other PRs are merged in.

**Comment by advayDev1** [comment]
changelog LG - might want to add that we've upgraded to Guava 19.0 full now

**Comment by brunobowden** [comment]
Added mention to changelog:

    Code quality:
    * Guava 19.0 system test (updated from Guava 18.0)

**Pull request merged**
