### PR TITLE
add i386 target - DO NOT COMMIT - doesn't work yet

### PR DESCRIPTION
**Pull request by brunobowden**
- list out Xcode tasks in comments
- rename j2objcForceCompilation => j2objcHackToForceCompilation

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - this commit is a work in progress and doesn't work yet. I'm trying to figure out how to add the i386 build target. 

Current warning I'm getting for it barfing on x86_64 target when it's looking for i386:

ld: warning: ignoring file /Users/brunobowden/dev/taptap/base/build/j2objcOutputs/lib/x86_64Debug/libbase-j2objc.a, file was built for archive which is not the architecture being linked (i386): /Users/brunobowden/dev/taptap/base/build/j2objcOutputs/lib/x86_64Debug/libbase-j2objc.a
Undefined symbols for architecture i386:

I'm speculating we should be the same as the j2objc libs and include all the architectures in a single fat file:
$ lipo -info ../j2objc-versions/j2objc-0.9.6.1/lib/libjre_emul.a 
Architectures in the fat file: ../j2objc-versions/j2objc-0.9.6.1/lib/libjre_emul.a are: x86_64 armv7 armv7s i386 arm64

**Comment by advayDev1** [comment]
btw, i've got i386 and x86_64 and fat working locally (and tested at least with simulator), I'll issue a PR.

**Comment by brunobowden** [comment]
Wonderful

**Comment by confile** [comment]
Sounds good!

**Comment by advayDev1** [comment]
See #124

**Pull request closed without merging**
