### PR TITLE
XcodeTaskTest remove incremental inputs + testing

### PR DESCRIPTION
**Pull request by brunobowden**
XcodeTask changes:
- Remove unused IncrementalInputs
- workingDir => setWorkingDir for convention on testing

XcodeTaskTest changes:
- Fairly complex testing of command line and Podfile / podspec outputs
- testXcodeConfig_Basic
- testXcodeConfig_NeedsPodInit
- testWriteUpdatedPodFileIfNeeded_NotNeeded

MockProjectExec:
- Added workingDir verification step
- Avoid string interpolation which throws exception for closure arg

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - PTAL. Main things are removing the unused incremental inputs on the XcodeTask and thorough testing of what it's doing.

**Comment by confile** [comment]
LGTM

**Comment by advayDev1** [comment]
@brunobowden - i thought we were adding a warning to open the .xcworkspace?

**Comment by brunobowden** [comment]
I'll do a separate PR for the warning.

**Pull request merged**
