### PR TITLE
First Draft of J2Objc Gradle Plugin sample app

### PR DESCRIPTION
**Pull request by confile**
Happy to get comments from you @brunobowden @advayDev1.

### CODE REVIEW

**Comment by advayDev1** [comment]
Awesome.  I'll take a look later today, this is a large PR =)

However, I think we need to fix #128 and #129 before we get this provably working, correct?

**Comment by confile** [comment]
I have a lot of things to improve. I am also not sure about a global build.gradle. Looking forward to your thoughts.

**Comment by brunobowden** [comment]
@confile - let's get the PR's from @advayDev1 merged in first and then make sure this works also. Once we get this in, it will be good to have this working as a continuous build. I can set that up as well.

**Comment by confile** [comment]
@brunobowden Not really know what this meant. Should I drop this request and you create it?

**Comment by brunobowden** [comment]
Here's the ordering on how events should happen:
1) @advayDev1 merge in PR #158 and #160 
2) You rebase your PR to include those changes
3) Fix your your sample app and then contact us again to take another look
4) Review process and fixes
5) Submit PR #175 

@confile - I hope that makes sense

**Comment by brunobowden** [comment]
So, you can keep the PR open for now.

**Comment by confile** [comment]
@brunobowden Yes, perfect. I renamed my master to samples this closes the current pull request. I will create a new one with my sample branch.

**Pull request closed without merging**
