### PR TITLE
Split system tests into 2 sets for Travis build time.

### PR DESCRIPTION
**Pull request by advayDev1**

### CODE REVIEW

**Comment by brunobowden** [comment]
LGTM. Smart idea. Naturally please wait until Travis completes successfully and check the output.

**Comment by advayDev1** [comment]
Sigh:

**Comment by advayDev1** [comment]
lol forgot link: https://www.traviscistatus.com/incidents/xn2svmgkq3xm

**Comment by advayDev1** [comment]
still waiting for travis.  will merge when green

**Pull request merged**
