### PR TITLE
Added jre_emul to default linkJ2objcLibs

### PR DESCRIPTION
**Pull request by confile**

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1 - this seems like it would be needed? Wanted to get your LGTM on this.

**Comment by advayDev1** [comment]
Does not LGTM.
https://github.com/j2objc-contrib/j2objc-gradle/blob/master/src/main/groovy/com/github/j2objccontrib/j2objcgradle/NativeCompilation.groovy#L299

I didn't keep this in the flags because you should not be able to turn off JRE.

**Comment by advayDev1** [comment]
Please reopen if you disagree.

**Comment by brunobowden** [comment]
Got it. I was a little surprised it worked without that but your code
reference makes sense.

**Comment by confile** [comment]
It is a little bit confusing. @advayDev1 At least add a comment in the config to make this clear.

**Pull request closed without merging**
