### PR TITLE
README: description and focus

### PR DESCRIPTION
**Pull request by brunobowden**
- Move Advanced Cycle Finder docs to FAQ
- Improve plugin description in README
- Minor changes to Folder Structure

### CODE REVIEW

**Comment by brunobowden** [comment]
@advayDev1, @confile - these are minor changes. I will update the plugin instructions once we confirm the fixes in the 0.3.0 release.

**Comment by confile** [comment]
LGTM

**Comment by advayDev1** [comment]
Lgtm if you remove string escaping from the new para in readme

**Comment by advayDev1** [comment]
Also the PR needs to be on the existing release branch not master if you
want this in .3

**Comment by brunobowden** [comment]
Fixed escaping. This is public documentation so it doesn't need to be in the branch.

**Pull request merged**
