### PR TITLE
xcodeTargetsManualConfig

### LINKED ISSUE #561: Config to only add j2objc_shared method to Podfile and not update targets
For a more complex Podfile with nested Ruby code, it may not be possible for the plugin to parse and correctly update the Podfile. In that case, it should have an option to:

1. Plugin only add / updates the `def j2objc_shared` method and doesn't make any other changes
1. Allow the user to manually edit the Podfile as needed

### LINKED ISSUE #562: Process or reject more complex Podfile situations
It may not be possible for plugin to effectively parse and update the Podfile - particularly when it includes complex ruby scripts. In this situation the plugin should:

1. Identify when it's a non-standard more complex Podfile
1. Process the Podfile if possible
1. If not possible to process, then fail the build with warning about disabling this with #561 

Example Podfile from this discussion:
https://groups.google.com/forum/#!topic/j2objc-discuss/crJsUkozk3Q

```
post_install do |installer|
  target = installer.project.targets.find{|t| t.to_s == "Pods-MagicalRecord"}
    target.build_configurations.each do |config|
        s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
        s = [ '$(inherited)' ] if s == nil;
        s.push('MR_ENABLE_ACTIVE_RECORD_LOGGING=0') if config.to_s == "Debug";
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s
    end
end
```

### PR DESCRIPTION
**Pull request by brunobowden**
- Manual config mode for Xcode targets in Podfile
- FAQ to explain how to use this
- Better "DO NOT MODIFY" lines for "pod method" + upgrade logic
- Fixes #561
- Fixes #562

### CODE REVIEW

**Comment by brunobowden** [comment]
@saruye - I hope you don't mind but I reworked your #565 PR. This made it more condensed and I believe more robust as well. Please take a look and let me know what you think. I'm keen to get the PR merged in ASAP as I'll be giving a presentation on it in the Bay Area to some startups.

**Comment by saruye** [comment]
hi. I looked through the code and it looks good to me. I think I tried to handle some more edge cases, like if there already is an empty line before the line where to insert the methods, don't add a second empty line and on where to insert new pod methods. But you are right that this is more robust now. 
Hope I was still able to help a bit!
The failing travis is only a travis problem I guess?!
If you are publishing any slides for the presentations I would be interested :)

**Comment by brunobowden** [comment]
Thanks @saruye, please take a closer look. When I'm writing that much code, I'm sure that I've made some mistakes and I'm not confident until some flaws have been discovered ;-) Likely the presentation will be recorded and posted online.

The build is failing on OS X due to the `install-osx-jdk7.sh` script failure whilst trying to install jdk7. I'm not sure what the problem is for that.

Btw, the old method you had before of `insertAtLineNumber`, turns out that there's an easy way to implement that in Groovy:

    podfileLines.addAll(lineNumber, insertLines)

That'll add in all the `insertLines` at the correct spot. Only one line required.

**Comment by brunobowden** [comment]
@saruye - v0.6.0 of the plugin has been published, please try this out and report back any issues

**Comment by saruye** [comment]
I didn't find time yet to look at it again :/ sry.  will test it on the weekend!

**Pull request merged**
