### PR TITLE
Override pod old pod definition if pod definition already exists…

### PR DESCRIPTION
**Pull request by confile**
…otherwise create a new pod definition. 

tested=yes

### CODE REVIEW

**Comment by confile** [comment]
@brunobowden This fixes your idea with relative paths of pod references. But instead of relative paths it overrides the pod reference on each build. Same effect.

**Comment by brunobowden** [comment]
This is very much not the same thing:

*Current Situation*
1) I download and build the sample project.
2) It will modify the PodFile to point to a new location in my home
directory.
3) When I look in Git, it will show PodFile as a modified file that it
wants me to commit
4) Every single damn time, I have to commit a change to project, the
PodFile will always show up
5) If someone accidentally checks in the file, then I see a change in a
file completely unrelated to the fix that they were actually making

The central point is that your home directory should never ever appear in a
shared codebase. If that's happening, then something is going wrong.

**Comment by confile** [comment]
Still having to much problems with the new plugin. As soon as I get it to work I take a look at it.

**Comment by confile** [comment]
Should I close this pull request?

**Comment by brunobowden** [comment]
@confile - please close this. Didn't mean you to waste work on this but I've just published a much more extensive reworking of the PodFile updating along with adding unit tests. See PR #211.

**Comment by brunobowden** [comment]
@confile - thanks for looking in to this. Closing as it's superseded by #211.

**Pull request closed without merging**
