### PR TITLE
Apply the JavaPlugin instead of just asserting it.

### PR DESCRIPTION
**Pull request by advayDev1**
Other plugins that extend Java (like GroovyPlugin) do the same thing.

### CODE REVIEW

**Comment by confile** [comment]
LGTM

**Comment by advayDev1** [comment]
Fixes #453

**Comment by brunobowden** [comment]
LGTM

I'd suggest adding a reference in the code (or at least this issue) pointing to the Gradle Groovy Plugin source where it does this.

**Comment by advayDev1** [comment]
done and merging

**Pull request merged**
