### PR TITLE
v0.5.0-alpha

### LINKED ISSUE #382: 0.5.0-alpha release
@brunobowden  - for discussing what should or shouldn't be in the eventual release.
there's a bunch of stuff marked in the milestone:

my personal goal is eliminate any code defects outside xcode/pods: https://github.com/j2objc-contrib/j2objc-gradle/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Atype%3Abug+-label%3Acat%3Axcode

### PR DESCRIPTION
**Pull request by brunobowden**
- Also updated link for publishing instructions
- Fixes #382

### CODE REVIEW

**Comment by advayDev1** [comment]
First do #543 please

**Comment by brunobowden** [comment]
@advayDev1, how should we interleave the e2e tests? Does it make sense to first update e2e with the current build. Once that passes all the tests, then merge in the version number change and carry on with the rest of the release process?

**Comment by advayDev1** [comment]
No you can merge in the version number change but hold off on the tag itself.  That way if it is broken, we just update

**Comment by advayDev1** [comment]
Ship it!  I'll push an e2e build as soon as you merge.

**Pull request merged**
